### ISSUE TITLE
Named exports in index.js

### ISSUE THREAD

**Issue by atomicpages** [pikapkg/pack#13]
A simple use case with named exports in `src/index.js` doesn't seem to be working:

```js
export { default as Test } from './components/Test';
```

.babelrc.js

```json
{
    "presets": [
        "@babel/preset-react",
        [
            "@babel/preset-env",
            {
                "useBuiltIns": "usage",
                "targets": "> 0.25%, not dead"
            }
        ]
    ],
    "plugins": [
        "@babel/plugin-proposal-object-rest-spread",
        "@babel/plugin-proposal-class-properties"
    ]
}
```

and our pipeline:

```json
"@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-standard-pkg"
      ],
      [
        "@pika/plugin-build-web"
      ],
      [
        "@pika/plugin-build-umd",
        {
          "name": "Test"
        }
      ]
    ]
  },
```

I must confess I haven't spent any time looking through the plugins -- I'll do that when I have some time 😬 

Edit: I forgot to add a the output. This is what I'm seeing in `dist-web`

```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "Test", {
  enumerable: true,
  get: function get() {
    return _Test.default;
  }
});

var _Test = _interopRequireDefault(require("./components/Test.js"));

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : {
    default: obj
  };
}
```

I'm not seeing the `component` folder.

**Comment by sandiiarov** [comment]
Probably because that file is living in dist-src folder?

**Comment by atomicpages** [comment]
No way for module to resolve without the path changing. Based on the [UMD docs](https://github.com/pikapkg/builders/tree/master/packages/plugin-build-umd):

> 1.Adds a UMD distribution to your built package: dist-umd/index.js
UMD Syntax
> 2. All dependencies bundled with the package.
> 3. Transpiled to run on all actively used and maintained browsers (excluding IE 11 and Opera Mini).
> 4. Adds a "umd:main" entrypoint to your built package.json manifest.

I think it should be in the same file?

**Comment by sandiiarov** [comment]
Yes, you are right. It is a bug. I can confirm that `@pika/plugin-build-node` has the same problem.

**Comment by sandiiarov** [comment]
If you use @pika/plugin-**ts**-standard-pkg and provide a full path to file:
`export { default as Test } from './components/Test/index';`
it is working as expected.

```js
  "@pika/pack": {
    "pipeline": [
      ["@pika/plugin-ts-standard-pkg"],
      ["@pika/plugin-build-node"],
      ["@pika/plugin-build-web"]
    ]
  }
```

**Comment by atomicpages** [comment]
Interesting 🤔 I'll dig around and see what's happening.

**Comment by FredKSchott** [comment]
Thanks for digging into this everyone! What also looks confusing here is that `dist-web/` should be using ESM syntax, but that code snippet seems to be Common.js. 

I'll take a deeper look as well later today.

**Comment by FredKSchott** [comment]
Okay, so the issue is that we read your `.babelrc` to help build your `dist-src/` source distribution, which is meant to be ES2018 + ESM. But by having `@babel/preset-env` in your `.babelrc` it was building your modern `dist-src/` for legacy browsers. Then the other plugins had trouble reading from that.

The fix for you is to remove `@babel/preset-env` from your `.babelrc`, and let @pika/pack handle the compiling for different environments for you.

I need to think about the best way to help others who run into this. Should we better document our expectations for the different distributions somewhere? Maybe a troubleshooting section?

**Comment by atomicpages** [comment]
@FredKSchott sweet! I'll give that a go tonight. Also, can some docs be added on how to setup/contribute to the project? I had to do some weird hacky workarounds to start debugging pack and the plugins 👍

**Comment by rix1** [comment]
> The fix for you is to remove `@babel/preset-env` from your `.babelrc`, and let @pika/pack handle the compiling for different environments for you.

Thanks @FredKSchott! This fixed the issue for me 👍

**Comment by sandiiarov** [comment]
> The fix for you is to remove `@babel/preset-env` from your `.babelrc`, and let @pika/pack handle the compiling for different environments for you

The problem is that Jest is using `@babel/preset-env`. Unfortunatly, I can't just remove it.

**Comment by atomicpages** [comment]
@sandiiarov you can configure `.babelrc` on a per-environment basis like this:

```js
{
    "presets": [], // any shared presets
    "plugins": [], // any shared plugins
    "env": {
        "test": {
            "presets": [
                [
                    "@babel/preset-env",
                    {
                        "targets": {
                            "node": "current"
                        }
                    }
                ]
            ],
            "plugins": ["@babel/plugin-proposal-object-rest-spread"]
        }
    }
}
```

when you run your tests you can do:

```bash
BABEL_ENV=test jest
```

See [api.env](https://babeljs.io/docs/en/config-files#apienv)

**Comment by FredKSchott** [comment]
^ TIL! I was going to suggest somehow exposing the "filename" option and then having some sort of `babelrc.pika.` override file, but I think that `env` solution may be our cleanest bet (open to other ideas tho!).

For whichever we choose, +1 for creating an example reference project with jest set up.

**Comment by ghengeveld** [comment]
Good thing I found this thread. I was able to get it all working by moving `@babel/preset-env` to the `test` env. Here's my setup: https://github.com/ghengeveld/react-async
