### ISSUE TITLE
Installation throws an error on Node 8

### ISSUE THREAD

**Issue by kapooostin** [pikapkg/pack#14]
It fails because of https://github.com/sindresorhus/new-github-release-url. Do you really need this dependency? It quite simple and its author seems to insist to ask for Node 10 for some obscure reasons.

**Comment by FredKSchott** [comment]
+1 for running on Node v8. Lets get rid of that dependency, and we should add some basic Travis tests on Node v8 as well.

**Comment by stramel** [comment]
+1

It would be nice to support all LTS Node versions. Maybe moving forward (after April) we can adhere to this? https://github.com/nodejs/Release

**Comment by FredKSchott** [comment]
👍 I think that's reasonable. I know we don't support Node v6 right now because we use `fs.copyFile` which is a v8.5.0+ feature, but assuming that we already run well on v8 I don't think there is anything v10+ that we are dying for.
