### ISSUE TITLE
CI and unit tests

### ISSUE THREAD

**Issue by DanielRuf** [pikapkg/pack#15]
We should have some CI setup to test pack itself (commands, results, Nodejs versions, ...).

**Comment by FredKSchott** [comment]
👍 This is a must have now that we've released. Thanks for creating an issue to track

**Comment by ryaninvents** [comment]
I've got some test coverage on the two Pika builders I have published ([1](https://github.com/ryaninvents/plugin-bundle-dependencies), [2](https://github.com/ryaninvents/plugin-bundle-zip)). Feel free to use them as a jumping-off point if you like.

**Comment by FredKSchott** [comment]
Nice! Will definitely check those out. They look awesome btw, do they work together or is it an either/or? I'd love to get an aws-lambda related [example project](https://github.com/pikapkg/examples) if you think that that's a reasonable use case for @pika/pack.

**Comment by ryaninvents** [comment]
@FredKSchott They'll eventually work together, but might each be useful individually. My plan is to use Terraform to deploy the dependencies as a Lambda layer, and the Lambda code itself would contain only `dist-node/index.js` for faster deployment. I have no doubt that folks will find other creative uses for a build step like this.

If you like, I can open an issue on the examples repo so we can continue discussing adding a Lambda example there :slightly_smiling_face:
