### ISSUE TITLE
Unclear, how to use only selected plugins

### ISSUE THREAD

**Issue by ezhikov** [pikapkg/pack#16]
*My config:*

```json
"@pika/pack": {
    "pipeline": [
      ["@pika/plugin-build-types"]
    ]
}
```

*Possibly helpful details:*
- Operating system: WSL Debian buster
- Node: 10.15.0

I'm getting next error:

```$ pack build
@pika/pack build v0.3.2
[1/4] Validating source...
[2/4] Preparing pipeline...
      ❇️  pkg/
[3/4] Running @pika/plugin-build-types...
      » no type definitions found, auto-generating...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run prepare stderr:
Error: Cannot find module '/work/monorepo/packages/utils/selectHelperMethods/pkg/dist-node/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Promise.resolve.then (/work/monorepo/node_modules/@pika/plugin-build-types/dist-node/index.js:103:63)
error Command failed with exit code 1.
```

*What I want to achieve*:

I wanted to only generate type declarations from .js and not sure why it look into `pkg/dist-node`, since I have single `index.js` in src.

If I have to run whole process of building for everything to generate types, can I, somehow, set destination folder, so it would be consistent across packages?

**Comment by FredKSchott** [comment]
That's right, currently you need to have generated a `node` dist to generate types automatically. This is a limitation of the automatic type generation, which imports the package via node to analyze it. 

This error message should definitely be more clear, and then the long term solution is to build off of the `dist-src` directory like all the other plugins.

If you're just trying to plug some automatic type generation into your existing build pipeline, Pack may be overkill. Check out https://github.com/Microsoft/dts-gen if you haven't yet.

**Comment by ezhikov** [comment]
Thank you. I'll try dst-gen. I don't need any more tooling for this particular case, so it should be enough.
