### ISSUE TITLE
Trying to publish package yields npm error since package is not scoped

### ISSUE THREAD

**Issue by peter** [pikapkg/pack#18]
I just tried doing "pack publish" for my little package awesome-type-check for the first time and got this error:

"[1/7] ✨  Prerequisite checks...
Error: Command failed: npm access ls-collaborators awesome-type-check
npm ERR! 
npm ERR! Usage: This command is only available for scoped packages."

**Comment by JohannesKlauss** [comment]
I am having the exact same issue.

**Comment by JohannesKlauss** [comment]
After doing some research, the solution is to upgrade npm via `npm i -g npm`, since npm 6.6 and 6.7 broke the `ls-collaborators` command. See [this issue](https://npm.community/t/npm-6-6-0-breaks-access-to-ls-collaborators/5101) for more info. It got fixed for npm 6.8
