### ISSUE TITLE
Instructions for contributors

### ISSUE THREAD

**Issue by reflog** [pikapkg/pack#19]
Hi.
Could you provide some basic instructions on building the project for contributors?
Right now there isn't anything in package.json scripts so not sure what way you use for building it...
Also a debugging instruction would be great.
There's a couple of things I wanted to fix and would be glad to get a leg up :)
Thank you in advance!

**Comment by FredKSchott** [comment]
+1, thanks for the suggestion. I've added some basic info here: https://github.com/pikapkg/pack/blob/master/CONTRIBUTING.md

I'd appreciate any help! If anything that you're wondering isn't covered in that document, feel free to ask it here as well.

**Comment by reflog** [comment]
@FredKSchott thanks! This is a great start.
How are you debugging pikapkg though? Right now, to test something I need to add console.log, then do 'yarn build', then `node --inspect-brk \dev\pack\pkg\dist-node\index.bin.js  publish` which isn't the most convenient :)

However I think I already found what previous issue I had with publish (seems to be related to 'execa' and me being on Windows).

Thanks again!

(p.s. the scripts section of package.json is not cross-platform. would you be interested in a pull request to fix that?)

**Comment by FredKSchott** [comment]
Hey @reflog, sorry for the delay getting back. Would love any help you can give, especially Windows related! I hate to admit that I've only tested this on my dev Mac & (a little) on Linux via Travis.

Adding a test framework are top of my TODO list so that contributors can create PRs confidently

**Comment by FredKSchott** [comment]
Closing this, with #20 continuing to track the testing work needed
