### ISSUE TITLE
Bundle extra files into pkg

### ISSUE THREAD

**Issue by stevefan1999-personal** [pikapkg/pack#26]
I have some assets files included in the source folder but it seems like pika is ignoring them and omitted `index.js` solely instead, and didn't choose to keep my template files alongside. What should I do to get them to be included as well?

**Comment by FredKSchott** [comment]
Do you have a link to your project where I could see it? 

The documentation for this still needs to be added (high of my TODO list), but the standard-pkg plugins assume this package structure:

```
- src/         # JavaScript/TypeScript Source
-   index.xxx  # Package Entrypoint
- assets/      # Any Non-JS Assets
```

**Comment by FredKSchott** [comment]
Check out the new [@pika/plugin-copy-assets](https://github.com/pikapkg/builders/tree/master/packages/plugin-copy-assets) plugin which makes this even more explicit (and flexible)
