### ISSUE TITLE
--any-branch does not seem to be implemented

### ISSUE THREAD

**Issue by ghengeveld** [pikapkg/pack#31]
When trying to publish from a branch other than `master`, this warning appears:

> Error: Not on `master` branch. Use --any-branch to publish anyway.

I tried passing this flag, to no avail. Looking at the [source code](https://github.com/pikapkg/pack/blob/8d52d8e64e185248b2f032babfeaf265a844cfb1/src/commands/publish.ts#L98) it doesn't seem to be implemented?

**Comment by FredKSchott** [comment]
Thanks for catching! np has a strange implementation of this that I think we just incorrectly adopted. Fixed on master, and will go out in the next release.

**Comment by jedahan** [comment]
Is there a straightforward way to use the current git build until the next release is published?

**Comment by FredKSchott** [comment]
Bah, thanks for pinging. Forgot that there was a release pending, just pushed it out now as `v0.3.5`
