### ISSUE TITLE
Tag specified while publishing preX version is not honored

### ISSUE THREAD

**Issue by ghengeveld** [pikapkg/pack#32]
I'm trying to publish a preminor version, but hitting this error:

> ? Select semver increment or specify new version **preminor 4.2.0-0**
> ? How should this pre-release version be tagged in npm? **next**
> ? Will bump from 4.1.2 to 4.2.0-0 and tag this release in npm as next. Continue? **Yes**
>
> [1/7] ✨  Prerequisite checks...
> Error: You must specify a dist-tag using --tag when publishing a pre-release version.

I would expect the `next` tag to be used as dist-tag, but it isn't.

Luckily, this works: `pack publish preminor --tag=next`

https://unpkg.com/react-async@4.2.0-0/ 🎉

FYI I'm updating https://github.com/ghengeveld/react-async to use @pika/pack.

**Comment by ghengeveld** [comment]
Well, that was unfortunate. It published a preminor version under the `latest` tag. Luckily I was able to unpublish it.

You see I don't want to just publish a completely new package structure without having thoroughly tested it first.

**Comment by FredKSchott** [comment]
Oof I'm so sorry that happened. Let me look right now to see why it didn't correctly honor the `--tag` value that you passed. 

A lot of this publish code came from https://github.com/sindresorhus/np, which is well tested, but maybe something broke when we integrated it into @pika/pack.

**Comment by FredKSchott** [comment]
Okay this was fixed in 1359971, and just pushed out as `v0.3.4`. Looks like we just weren't honoring any of the flags correctly, huge thanks for catching!

**Comment by ghengeveld** [comment]
Good work! Thanks for fixing it so quickly.
