### ISSUE TITLE
node/web builds failing with no warning message?

### ISSUE THREAD

**Issue by tnrich** [pikapkg/pack#36]
I'm still seeing relative imports in the node and web files for my repo: 

https://github.com/TeselaGen/ve-sequence-utils/tree/pikaTryout

I am using 

```
"@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-standard-pkg",
        {
          "exclude": [
            "__tests__/**/*"
          ]
        }
      ],
      [
        "@pika/plugin-build-node"
      ],
      [
        "@pika/plugin-build-web"
      ],
      [
        "@pika/plugin-build-types"
      ]
    ]
  },
```

and here's the output I get when running it: 
```
ve-sequence-utils tnrich$ pack build
@pika/pack build v0.3.4
[1/7] Validating source...
[2/7] Preparing pipeline...
      ❇️  pkg/
[3/7] Running @pika/plugin-standard-pkg...
Unexpected file extension: ./prepareRowData_output1.json
      📝  pkg/dist-src/index.js [esnext]
      » Linting with standard-pkg...

pkg/dist-src/index.test.js
  ⚠️  [5:15] `__dirname` is not a valid ESM global. Use `import.meta.url` instead.
pkg/dist-src/prepareRowData_output1.json
  ⚠️  Only JavaScript files are expected in your dist-src/ distribution.
pkg/dist-src/prepareRowData.test.js
  ⚠️  [5:0] "./prepareRowData_output1.json": Valid relative imports must include the ".js" file extension.

✘ 3 issues found.
[4/7] Running @pika/plugin-build-node...
      📝  pkg/dist-node/index.js [main]
[5/7] Running @pika/plugin-build-web...
      📝  pkg/dist-web/index.js [module]
[6/7] Running @pika/plugin-build-types...
      » no type definitions found, auto-generating...
Error: Cannot find module './getAllInsertionsInSeqReads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/tnrich/Sites/ve-sequence-utils/pkg/dist-node/index.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

Here's the built node file where you can see the relative imports: 

https://github.com/TeselaGen/ve-sequence-utils/blob/pikaTryout/pkg/dist-node/index.js

Do I need to solve all those warning messages to get my repo to build correctly, or are those red herrings and is there something else going on? Thanks!

**Comment by FredKSchott** [comment]
Those three warnings are valid:
- __dirname is Node specific, and would fail in the browser
- importing JSON is Babel specific, and would fail in the browser
- JSON files should live outside of your src/ directory so that they aren't duplicated across different distributions. Move any JSON into an `assets/` directory, and then see https://github.com/pikapkg/builders/tree/master/packages/plugin-copy-assets to copy you assets folder from `assets/` -> `pkg/assets/`. (We should have an example that shows this).

**Comment by tnrich** [comment]
@FredKSchott okay, I can fix those, but I don't think any of them explain why the build is failing.. or do they? That is what I'm confused about. Clearly the build failed, but are those warnings the reason it did?

**Comment by FredKSchott** [comment]
It's hard to say without running it myself on my machine, so I'm not positive that that's the reason. but it would definitely be my first guess, and even if you fix the failing build those issues will probably still prevent the built package from running.
