### ISSUE TITLE
[Feature request] Permit plugins to further modify package.json

### ISSUE THREAD

**Issue by ryaninvents** [pikapkg/pack#46]
Due to historical reasons, I'm interested in publishing a package with a `lib/` directory containing CommonJS-compatible code. I've got most of my plugin written, but have discovered that `@pika/pack` contains [hardcoded values](https://github.com/pikapkg/pack/blob/6ea20563a6/src/util/normalize-manifest/for-publish.ts#L53-L74) preventing me from publishing my `lib/` directory. (I'd share the plugin, but it's internal and I don't own the IP.)

I understand that there may be potential trust issues with allowing builders further control over package.json, but I think it's worth discussing. It might also open the door for builders to do things like:

- Auto-populate [homepage](https://github.com/pikapkg/pack/blob/6ea20563a6/src/util/normalize-manifest/for-publish.ts#L59) and [bugs](https://github.com/pikapkg/pack/blob/6ea20563a6/src/util/normalize-manifest/for-publish.ts#L60) fields
- [Man pages](https://github.com/pikapkg/pack/blob/6ea20563a6/src/util/normalize-manifest/for-publish.ts#L63) from README.md or a `docs` folder
- Automated [contributors list](https://github.com/pikapkg/pack/blob/6ea20563a6/src/util/normalize-manifest/for-publish.ts#L62) from GitHub API or Git history (GitHub API for public projects, Git history for internal)

I'd be happy to work on this; I just want to make sure it aligns with the overall project direction for `@pika/pack` before I do anything.

**Comment by FredKSchott** [comment]
So we actually do support this! Check out these lines of code that run beforehand:

https://github.com/pikapkg/pack/blob/6ea20563a6/src/util/normalize-manifest/for-publish.ts#L41-L51

Plugins are able to define and export a `manifest` function that takes in the existing manifest and modifies it as needed. See most of our official build plugins for examples: https://github.com/pikapkg/builders

```
export function manifest(manifest) {
  manifest.types = manifest.types || "dist-types/index.d.ts";
}
```

Does that meet the needs for your project? LMK if I missed or misunderstood anything.

**Comment by ryaninvents** [comment]
Close! I'm using the `manifest` functionality, but unfortunately the ordering of the return value kills my changes:

```javascript
function currentImplementation() {
  return {
    ...newManifest,
   files: [ /* ... */ ],
   dependencies: { /* ... */ },
   // etc
  }
}

function proposedImplementation() {
  return {
   files: [ /* ... */ ],
   dependencies: { /* ... */ },
   // etc, but then:
   ...newManifest
  }
}
```

Since keys after the spread operator override those keys in your spread object, even though I'm using `manifest` to modify the package.json, they get clobbered in the final stage. Somewhat similar to the behavior of `Object.assign({}, newManifest, originalManifest)` compared to `Object.assign({}, originalManifest, newManifest)` if both objects share common keys.

**Comment by FredKSchott** [comment]
That's a great point. I think that original ordering was just me being conservative about giving plugins too much freedom to mess with the manifest, but your usecase makes sense. Moving all of those default properties into the creation of the original `newManifest` object sounds like a good solution, which then gives plugins final control over manifest. What do you think?

```js
  const newManifest = { /* combine the existing newManifest object with the existing return object  };
  // pass newManifest through each plugin's `manifest()` function.
  return newManifest;
```

**Comment by ryaninvents** [comment]
Yeah, that sounds good! Good call on being conservative initially, since this could definitely turn into a footgun. Let me know if I can contribute in any way to a PR.

**Comment by peanutbother** [comment]
are there any news on this?

**Comment by FredKSchott** [comment]
Looks like I did the work on this a while ago and just had it sitting in my local dir 🤦‍♂ Will go out with next release!

**Comment by peanutbother** [comment]
in the meantime I made a plugin which lets you define values that are inserted into `package.json`
https://github.com/jabuco/pika-plugin-merge-properties
maybe that helps for some advanced scenarios.

let me know if I should publish it

**Comment by FredKSchott** [comment]
That's great! Sorry again for the delay getting this out.

This probably has a real, valuable use-case even with the above fix. We're explicit in only pulling in officially supported npm package.json properties (all documented here: https://docs.npmjs.com/files/package.json) since most others are build config only. But I am sure there are some valid reasons to need additional properties copied over to the production build.

If you are able to publish, I'd be happy to link it in our "community plugins" section!

**Comment by peanutbother** [comment]
sure I'll publish it tomorrow let me know what tests to include or if you'd like to I'd be happy for suggestions to improve this plugin.

**Comment by peanutbother** [comment]
Alright version 1.0.2 is publicly available now;
https://github.com/jabuco/pika-plugin-merge-properties

Let me know if there are issues.
Also I made a similar plugin which add values defined in plugins properties.
https://github.com/jabuco/pika-plugin-add-properties

The second one probably is meeting pika/pkg  standards more since it uses values that aren't in the root scope of package.json but rather copies the properties from plugin config to build target package.json

I'm open for suggestions plus I appreciate issue reports and pull requests. cheers.
