### ISSUE TITLE
[Question] - package.json overwritten

### ISSUE THREAD

**Issue by semoal** [pikapkg/pack#47]
Hi!

I'm building a date helper library for my React projects and I'm having some issues with:
```npm pack```

1. I run: ```pack build ```, and generates a pkg folder with correct package.json
2. I execute, ```npm pack```for generating a tgz, to test it before publishing. 

Here comes the problem, original package.json is being copied in _pkg_ folder, so when I import the package to a real project it's says doesn't exist anything (of course, because this package.json is wrong).

I've tried adding a .npmignore with package.json but doesn't work.

Have you got any suggerence?

Thanks in advance

**Comment by ryaninvents** [comment]
Try this:

```bash
npm pack file:./pkg
```

You might also consider using `npm link`. Unfortunately, Pack does not interact well with this command, since `npm link` creates a `pkg/node_modules` directory, but Pack deletes your `pkg` directory before building it. Here's my workflow for MacOS/Linux:

```bash
# Run only once, to register your package
(cd pkg && npm link)

# Run after you rebuild, to get `node_modules` back
# without having to reload all packages over the network
(cd pkg && ln -s ../node_modules)

# Then, in the package where you want to test it:
npm link mypackage
```

**Comment by semoal** [comment]
Thanks you Ryan!
