### ISSUE TITLE
[Suggestion] Bump version after successful build of package

### ISSUE THREAD

**Issue by JohannesKlauss** [pikapkg/pack#48]
Right now the third step is to bump the version and the fourth step is to build the package. But when pack fails to build the package, you are stuck with an already tagged commit in the branch and you have to revert a lot of stuff.
It would be easier to fix errors inside the package building process if you wouldn't have to revert the commited tag all the time.

**Comment by FredKSchott** [comment]
+1. that's what the prerequisite step is trying to do (catch as many errors ahead of time as possible) but obviously that will never be 100% perfect.

Do you have a specific example of which step is failing, just so I know?

I wonder if we could automate the rollback if something does go wrong... we already require a clean git tree, we could just `git reset --hard STARTING_COMMIT && git tag -d FAILED_TAG` as needed.

**Comment by stramel** [comment]
Could we instead bump without a tag and then tag post build?

**Comment by JohannesKlauss** [comment]
The compilation from TypeScript to JavaScript is failing in my project with a generic TS error. I don't think it's pika related, but I am still investigating.

The git reset sounds good and should cause no problems.

**Comment by JohannesKlauss** [comment]
So I checked this and the pika packager is not responsible for the failing TS build. So there should be some kind of safety net when something fails.
