### ISSUE TITLE
Invalid Tag Name on Github Release Draft after publishing

### ISSUE THREAD

**Issue by JohannesKlauss** [pikapkg/pack#59]
<img width="720" alt="Bildschirmfoto 2019-06-17 um 15 42 23" src="https://user-images.githubusercontent.com/6214415/59608885-995fa100-9116-11e9-85ee-74d7ed58d5c7.png">

Hey guys, I have to say: Extremely well done update. The new version feels extremly smooth and comprehensive.
However I encountered one issue. After publishing and getting redirected to the Github Release Draft page the Tag name is invalid because of the symbols before the actual version (see image).

**Comment by FredKSchott** [comment]
Hey, thanks for the message @JohannesKlauss! In the latest version, we just call out to https://github.com/sindresorhus/np directly, so this is mostly likely a bug in their library. 

If you can send me a link to the repo I can try to take a look, but unfortunately this logic isn't a part of our codebase anymore

**Comment by JohannesKlauss** [comment]
Ah, ok. So I'll open up an issue over there. thx
