### ISSUE TITLE
"dist-src/" does not exist, or was not yet created in the pipeline.

### ISSUE THREAD

**Issue by YerkoPalma** [pikapkg/pack#6]
Hi 👋 

I'm having troubles running the build command, following what readme says. 

with this config

```
"@pika/pack": {
    "pipeline": [
      [ "@pika/plugin-standard-pkg" ],
      [ "@pika/plugin-build-web" ]
    ]
  },
```

I get this error

![image](https://user-images.githubusercontent.com/5105812/52439576-9dd9d480-2afa-11e9-997a-5a0f6cd37830.png)

I'm running node v11.5.0 and npm v6.4.1 and working on with git-bash on windows 10

Any ideas how to fix this error?

**Comment by FredKSchott** [comment]
Hmm, I bet this is a windows path issue (if you have a Linux or Mac system, it would be great if you could try there to confirm that this is windows specific). 

I’ll plan to spin up my VM and debug this tonight/tomorrow if no one has been able to fix it sooner

**Comment by YerkoPalma** [comment]
Honestly, I also though it was some windows related issue, but the same happens on an ubuntu machine

![image](https://user-images.githubusercontent.com/5105812/52440516-19d51c00-2afd-11e9-9c4e-6b6f8a955749.png)

Here is my full project, in case is some particular error of it
https://github.com/YerkoPalma/compass

**Comment by FredKSchott** [comment]
Oh interesting, let me take a look on my machine then.

**Comment by FredKSchott** [comment]
Actually, looking at your project, I think the error is really happening in the previous plugin.

@pika/pack assumes a standard package structure, where your source code lives in a ‘src’ directory. To use pika, you’ll want to move your source JS code (including index.js) to a src/ directory. assets/ can remain top-level.

Btw this is 100% something that needs to be documented better in the README.

**Comment by YerkoPalma** [comment]
Oh! that was unexpected. 
You are right, moving every js file to a `src` folder fix it.

Thanks

**Comment by FredKSchott** [comment]
No problem! Thanks for testing this out!

If you don’t mind, im going to leave this issue open to track:
- documenting this structure better
- why didn’t the source builder catch that?

**Comment by YerkoPalma** [comment]
Ok, no problem. 

IMO this should be a configurable option 👍

**Comment by ithinkihaveacat** [comment]
+1 please document the state the package needs to be in before running `@pika/pack`!

From reading the docs (e.g. "This lets @pika/pack build your package without much (if any) configuration required on your part"), I got the impression that no particular setup would be required.

(This did sound a bit too good to be true, but I don't have a great understanding of how npm packages are made (hence my interest in this project…), so I thought this might actually be possible.)

FWIW the reduced test case I put together before finding this issue is at https://github.com/ithinkihaveacat/pack-test.

**Comment by matiascarranza** [comment]
+1 for adding this to the docs & configuration option

**Comment by FredKSchott** [comment]
I have a draft of the blog post I plan to release asap that goes into more detail on the package structure. You can view it here: https://next.pikapkg.com/blog/a-standard-package-format (very much in draft form, some things may change before release, please leave feedback if you have any, etc!)

The plan would be to post that, clean up the standard-pkg README, and then link to the two in all the relevant places (@pika/pack, dependent plugin READMEs, etc)

**Comment by FredKSchott** [comment]
Error message fixed here: https://github.com/pikapkg/builders/commit/b2e5a8bb4dd504c97f643cac7ebfe7a6eafdddc1

Will go out in the next release

**Comment by zoltanbedi** [comment]
I'm facing this issue as well. Not sure how to resolve it. Tried with wsl and windows. the pkg folder is not created.
