### ISSUE TITLE
Node and web versions don't compile

### ISSUE THREAD

**Issue by selfagency** [pikapkg/pack#60]
I'm having the same issue as #7.

![Screen Shot 2019-06-17 at 4 12 33 PM](https://user-images.githubusercontent.com/2541728/59633564-be561300-911a-11e9-9c04-ed347356716b.png)

My packages aren't compiling down to a single file for web or node, nor including the modules in their respective folders, but are referring to the absent modules.

Here's my `dist-web/index.js`, for example:

```
Object.defineProperty(exports, "__esModule", {
  value: true
});
Object.defineProperty(exports, "_case", {
  enumerable: true,
  get: function get() {
    return _case2["default"];
  }
});
Object.defineProperty(exports, "_hash", {
  enumerable: true,
  get: function get() {
    return _hash2["default"];
  }
});
Object.defineProperty(exports, "_md", {
  enumerable: true,
  get: function get() {
    return _md2["default"];
  }
});
Object.defineProperty(exports, "_punc", {
  enumerable: true,
  get: function get() {
    return _punc2["default"];
  }
});
Object.defineProperty(exports, "_trunc", {
  enumerable: true,
  get: function get() {
    return _trunc2["default"];
  }
});

var _case2 = _interopRequireDefault(require("./modules/_case.js"));

var _hash2 = _interopRequireDefault(require("./modules/_hash.js"));

var _md2 = _interopRequireDefault(require("./modules/_md.js"));

var _punc2 = _interopRequireDefault(require("./modules/_punc.js"));

var _trunc2 = _interopRequireDefault(require("./modules/_trunc.js"));

function _interopRequireDefault(obj) {
  return obj && obj.__esModule ? obj : {
    "default": obj
  };
}
```

This is resulting in errors loading my packages:

```
Server running at http://localhost:1234
🚨  /Users/daniel/code/kifa-web/node_modules/@selfagencyllc/dev-tools-text/dist-web/index.js:35:44: Cannot resolve dependency './modules/_case.js' at '/Users/daniel/code/kifa-web/node_modules/@selfagencyllc/dev-tools-text/dist-web/modules/_case.js'
  33 | });
  34 |
> 35 | var _case2 = _interopRequireDefault(require("./modules/_case.js"));
     |                                            ^
  36 |
  37 | var _hash2 = _interopRequireDefault(require("./modules/_hash.js"));
  38 |
^C⏎
```

Here's the entry file being compiled:

```
/* Modules */
import _case from './modules/_case'
import _hash from './modules/_hash'
import _md from './modules/_md'
import _punc from './modules/_punc'
import _trunc from './modules/_trunc'

/* Exports */
export { _case, _md, _hash, _punc, _trunc }
```

**Comment by semoal** [comment]
In my case this issue was caused by being used @babel/preset-env on .babelrc.

**Comment by ryaninvents** [comment]
You can use `@babel/preset-env` as long as you set `"modules": false` in the options. Same with `babel-preset-react-app`, you have to set `"useESModules": false`. Keep in mind that you'll either need to use the `env` field in your `.babelrc` to allow modules to transpile during tests, or else set up `babel-jest`.

**Comment by selfagency** [comment]
Still having the same issue with this config:

```
  "@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-standard-pkg",
        {
          "exclude": [
            "tests/**/*.js"
          ]
        }
      ],
      [
        "@pika/plugin-build-node"
      ],
      [
        "@pika/plugin-build-web"
      ]
    ],
    "modules": false
  },
```

**Comment by semoal** [comment]
> Still having the same issue with this config:
> 
> ```
>   "@pika/pack": {
>     "pipeline": [
>       [
>         "@pika/plugin-standard-pkg",
>         {
>           "exclude": [
>             "tests/**/*.js"
>           ]
>         }
>       ],
>       [
>         "@pika/plugin-build-node"
>       ],
>       [
>         "@pika/plugin-build-web"
>       ]
>     ],
>     "modules": false
>   },
> ```

The modules false goes in .babelrc options of preset env, not in @pika/pack
For me worked perfectly, thanks @ryaninvents
