### ISSUE TITLE
Automatically convert "not modern" packages in Pika CDN

### ISSUE THREAD

**Issue by filips123** [pikapkg/pack#62]
Pika CDN currently fails if the package is "not modern", without "module" entrypoint. This is not good because many packages aren't using that entrypoint which means users can't use them through Pika CDN.

Is it possible to automatically convert that packages to "modern" ones with Pika Pack when the user requests them? Conversion should be used the only first time when the package is requested and the result should be cached for each package version.

**Comment by FredKSchott** [comment]
+1, this has been suggested in the pika/web repo: https://github.com/pikapkg/web/issues/62 feel free to continue discussing there
