### ISSUE TITLE
`npm access ls-collaborators X` Package not found

### ISSUE THREAD

**Issue by JohannesKlauss** [pikapkg/pack#63]
When trying to publish a brand new package I get an error during the User auth verification:

```
✖ Command failed: npm access ls-collaborators react-use-fetch-factory
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/-/package/react-use-fetch-factory/collaborators?format=cli - Package not found

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/johannesklauss/.npm/_logs/2019-07-10T11_47_21_798Z-debug.log
```

Which of course fails because the package doesn't exist yet on the registry.
After publishing the initial release via `npm publish` everything works fine.

**Comment by FredKSchott** [comment]
Sounds like you won't be able to reproduce now that react-use-fetch-factory is published, but have you updated to @pika/pack v0.4.0? The latest version of the library no longer implements its own publish flow, and instead just calls out to `np` directly.

**Comment by JohannesKlauss** [comment]
Yes, I am using 0.4.0
Should I open the issue in `np` then?

**Comment by FredKSchott** [comment]
It seems like an issue already exists in their repo: https://github.com/sindresorhus/np/issues/339 where updating npm fixes the issue

**Comment by JohannesKlauss** [comment]
This is a different error message. I'll open a ticket in `np`.
