### ISSUE TITLE
How may we handle packages from source control?

### ISSUE THREAD

**Issue by trusktr** [pikapkg/pack#66]
One downside of the separate-folder-for-publishing approach is that the package isn't installable from source control.

F.e. `npm install github:username/package#hash`. The package will be installed, and will have a `pkg` folder inside of it, so the version installed from source control has a different final structure than the one installed from npm.

Any ideas for this case?

**Comment by FredKSchott** [comment]
If you check your built package into source-control, then I guess you could import from 'package-name/pkg' on any installed-from-github package. But I'm not necessarily recommending that you do that.

I believe this problem affects any package that has a build step, where you'll need to check the built files/pkg into source, and then you can reference it.

Funny enough, I'm getting ready to launch something for this exact problem, so stay tuned on that
