### ISSUE TITLE
Improve NPM Publish experience when using TFA

### ISSUE THREAD

**Issue by atomicpages** [pikapkg/pack#70]
Current message when using TFA with `npm publish` is kind of ambiguous. Pika shows a simple message: 

```
Publishing package using npm (waiting for input…)
```

It might be better to specifically call it out saying that the user needs to enter in the token generated from their authentication app.

**Comment by FredKSchott** [comment]
Hey @atomicpages! Which version of @pika/pack are you using? If you're not on the latest version, try updating and re-running (the new command is `pika publish`) and let me know if you're still having trouble.

**Comment by atomicpages** [comment]
Using the latest: 0.5.0 :(

**Comment by FredKSchott** [comment]
Huh, that's really strange... the implementation has been totally moved out of Pika and now just basically calls `npx np` with a pika-specific set of options:  https://www.npmjs.com/package/np

Unfortunately there's nothing we can do if np is hanging :(

**Comment by atomicpages** [comment]
Hmmm, let me dig in some more. It seems like my npm log in info isn't being read so I need to keep logging in. 

I should clarify here that it's not really hanging. It's expecting me to enter in my token. I'm saying the message coming from `np` is really misleading.

**Comment by FredKSchott** [comment]
Yea, that's strange. I wonder if there's a message coming from npm (specifically asking for the token) that's never actually being output to the console
