### ISSUE TITLE
@pika/cli isn't included in @pika/pack

### ISSUE THREAD

**Issue by kysley** [pikapkg/pack#71]
A big hello to the @pikapkg team :) 

I ran into an interesting issue when installing @pika/pkg. I used the following command: 
`sudo npm i -g @pika/pack`.

It doesn't appear that it adds the binary to PATH (taking a stab at how you guys add the `pika` command). Commands like `pika`, and `pack` are unrecognized. The only recognized command is `pika-pack publish` (which is now deprecated?).

I looked into your release notes for `v0.5`, saying that @pika/cli should be included, but it doesn't seem to be 😕. The issue was resolved by running `sudo npm i -g @pika/cli` myself.

**Comment by manobi** [comment]
The same for me. It's not working locally or globally.

**Comment by FredKSchott** [comment]
Thanks for reporting, the CLI is a dependency, so it sounds like npm doesn't bin-link a package's dependencies when you install in globally (which makes sense).

If you installed @pika/pack in a project, @pika/cli would get installed with it, and `npx pika pack` would work fine. 

Let me add a note to the README about installing @pika/cli globally.

**Comment by FredKSchott** [comment]
Note added, lmk if that makes more sense
