### ISSUE TITLE
⭐️ Discussions moved to Pika Discuss

### ISSUE THREAD

**Issue by FredKSchott** [pikapkg/pack#73]
We're testing out a new tool for managing support, feedback and feature requests in open source projects. To create a new issue or search existing discussions, go here:
👉 **https://www.pika.dev/packages/@pika/pack/discuss** 👈

<a href="https://www.pika.dev/discussions"><img width="1217" alt="Screen Shot 2019-09-10 at 8 25 05 PM" src="https://user-images.githubusercontent.com/622227/64665919-3c1f7700-d409-11e9-86ef-5b27db30f50e.png"></a>

This repo's GitHub issue tracker will continue to operate for issues (verified bugs) ONLY. All other new issues will be closed or automatically migrated.  [Learn more...](https://www.pika.dev/discussions)

**Comment by tunnckoCore** [comment]
Aaahh... again. Isn't it better to have everything in one place? I don't understand the people doing that. I don't like that. What's the so big problem of GitHub Issues? If it's a "verified bug" it will have `bug` label and that's it. Why you should move out of the place where you're 99% of the time when you're not in your code editor? I don't get it. Same thing for those moving to Spectrum or such. It's only good if you have customers and clients that may don't really understand what GitHub is or something along these lines, then it's acceptable to have such forum, but even then - you only need StackOverflow or encourage chat or twitter support - something that is near and acceptable to them, the clients.

But when you have a product that is used by a developer community, then it really doesn't make much sense to me, it may create more friction than it helps. Can you elaborate on that, what's your view and thoughts?

**Comment by FredKSchott** [comment]
All of the reasons for this are outlined on the overview page, linked above. Here it is again, since it sounds like you didn't read it: https://www.pika.dev/discussions

If you did read it but just disagree, that's fine. No ones forcing you to use it yourself :)

**Comment by tunnckoCore** [comment]
No, I did. The thing is that I don't see (what can be) the difference and the plus of using external service. GitHub has bots, actions, labels, search, filtering, milestones, assigning users and etc, what's the benefit of something other? What's exactly the problem of GitHub Issues, for you? I'm just trying to see it from a different point.

I'm not just plain arguing: a) in recent years I more and more seeing similar things pop up; and b) you should try to sell it to a user, harder ;p

CMR,
:wink:
