### ISSUE TITLE
Add prettier bot (format on merge)

### ISSUE THREAD

**Issue by FredKSchott** [pikapkg/pack#77]
Follow up from #75 

 I'm sure there are bots that you can have run after every PR merge, or even every commit, to format / run prettier. If anyone knows of any, I'd love to experiment with adding one

/cc @dangodev

**Comment by drwpow** [comment]
The difficult part I think is having the bot run _and_ safely commit to Git history only when necessary.

One way to do this would be to use `prettier --check src/**/*.ts` and have GitHub Actions or Travis or something run this check on every PR. If it needs formatting, the PR author runs `npm run format` and pushes again.

**Comment by ghost** [comment]
@FredKSchott @dangodev What about [lint-staged](https://github.com/okonet/lint-staged)?
