### ISSUE TITLE
No longer logging build error info

### ISSUE THREAD

**Issue by FredKSchott** [pikapkg/pack#78]
@pika/pack is no longer reporting some error output. This is especially annoying with TS/Babel build, where you don't get any build error output, just an exception saying which command failed.

We use "execa" behind the scenes, my guess is that something might have changed there.

**Comment by alexlafroscia** [comment]
I think I'm getting bitten by this too; I'm trying to use the TypeScript builder and get an error when running `pika build`, but it's entirely unclear what the error actually is. Had to give up on using Pika because running `tsc` directly works just fine 🤷‍♂ 

This is all I get

```
Error: Command failed with exit code 2 (ENOENT): /Users/alafroscia/Code/mi/page-objects/node_modules/typescript/bin/tsc --outDir /Users/alafroscia/C
ode/mi/page-objects/packages/page-objects/pkg/dist-src/ -d --declarationDir /Users/alafroscia/Code/mi/page-objects/packages/page-objects/pkg/dist-ty
pes/ --project /Users/alafroscia/Code/mi/page-objects/packages/page-objects/tsconfig.json --target es2019 --module esnext --noEmit false
    at makeError (/Users/alafroscia/Code/mi/page-objects/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/alafroscia/Code/mi/page-objects/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Command failed with exit code 1 (EPERM): npx pika-pack
    at makeError (/Users/alafroscia/Code/mi/page-objects/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/alafroscia/Code/mi/page-objects/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by FredKSchott** [comment]
Fixed in 37e3af0a7b16cbd75c828731f330a64f7d8d2da8 and going out now, thanks for your patience!

**Comment by FredKSchott** [comment]
Fixed in https://github.com/pikapkg/builders/commit/37e3af0a7b16cbd75c828731f330a64f7d8d2da8 and going out now, thanks for your patience!

**Comment by alexlafroscia** [comment]
Awesome, looks like things are working now!
