### ISSUE TITLE
"Publish" version downgrade in Latest?

### ISSUE THREAD

**Issue by Saeris** [pikapkg/pack#80]
After upgrading `@pika/pack` to `latest` (`^0.5.0`) from version `^0.4.0`, I've noticed that the publish command has rolled back to a previous version that's broken on Windows since it uses `np` under the hood.

My console is showing:

`@pika/pack publish v0.3.6` when running `pack publish` whereas on the previous version showed `@pika/pack publish v0.4.0`

I upgraded because I kept running into an "Unknown system error" on Yarn Publish:

```bash
  √ Prerequisite check
  √ Git
  √ Prerequisite check
  √ Prerequisite check
  √ Git
  ↓ Cleanup [skipped]
  √ Installing dependencies using Yarn
  √ Running tests using Yarn
  √ Bumping version using Yarn
  × Publishing package using Yarn
    → The project was rolled back to its previous state.
    Pushing tags
    Creating release draft on GitHub

× Error publishing package:
Command failed with exit code 1 (Unknown system error -1): yarn publish pkg/
```

I tried running `yarn publish pkg/` manually to see what the error was, and received none, however was prompted for my OTP, which may have been the source of the error, if there was a change to Yarn and it was unhandeled in the publish script.

Would be great if this could be fixed asap! Sorry to drop this request so close to the holidays!

**Comment by FredKSchott** [comment]
Hey @Saeris sorry for missing this over the holidays. There was some moving around of the `bin` name, but as of v0.5.0 you should run `pika pack` inside of any npm/yarn script to run. Or, `npx @pika/pack` in your terminal yourself works as well. My guess is that you're using an old alias, which is triggering an old version.

Publish responsibility was moved out of @pika/pack and into our CLI, so I'd add a "publish" npm/yarn script that runs `pika publish`. That always pulls the latest version of `np` (unless you've installed `np` locally as a devDependency, in which case it uses that version). Give that a try, hopefully it should work
